-- Hub 📈 DIGITAL MARKETING (khoá L02, 11 module × 10 từ) — SINH TỰ ĐỘNG bởi tools/dm_hub_gen.py, đừng sửa tay.
-- Đặt Hub ngay SAU Hub EA2025 (id hub_ea2025); không thấy EA thì đặt cuối.
begin;
do $$ declare ea int; begin
  if exists (select 1 from hubs where id = 'hub_digital_marketing') then return; end if;
  select sort into ea from hubs where id = 'hub_ea2025';
  if ea is null then select coalesce(max(sort), 0) into ea from hubs; raise notice 'Không thấy Hub EA -> đặt cuối'; end if;
  update hubs set sort = sort + 1 where sort > ea;
  insert into hubs (id, code, name, sort, name_en, name_zh) values ('hub_digital_marketing', 'DIGITAL_MARKETING', '📈 DIGITAL MARKETING', ea + 1, '📈 DIGITAL MARKETING', '📈 数字营销');
end $$;
insert into notebooks (id, hub_id, name, icon, sort, name_en, name_zh) values ('nb_dm_l02', 'hub_digital_marketing', 'Digital Marketing cho người mới (L02)', '📈', 1, 'Digital Marketing for Beginners (L02)', '数字营销入门 (L02)')
  on conflict (id) do update set name = excluded.name, icon = excluded.icon, name_en = excluded.name_en, name_zh = excluded.name_zh;
insert into sections (id, notebook_id, name, sort, name_en, name_zh) values ('nb_dm_l02_s1', 'nb_dm_l02', '11 MODULE', 1, '11 MODULES', '11 个单元')
  on conflict (id) do update set name = excluded.name;
-- Module 00
insert into pages (id, section_id, name, sort, name_en) values ('nb_dm_l02_s1_p00', 'nb_dm_l02_s1', '⚙️ 00 — Cài đặt công cụ', 1, '00 — Tool setup') on conflict (id) do update set name = excluded.name, sort = excluded.sort, name_en = excluded.name_en;
insert into batches (id, page_id, name, sort, created_at, name_en) values ('nb_dm_l02_s1_p00_b1', 'nb_dm_l02_s1_p00', 'Từ vựng', 1, 1791100000000, 'Vocabulary') on conflict (id) do update set name = excluded.name;
insert into blocks (id, batch_id, name, global_index, sort) values ('nb_dm_l02_s1_p00_b1_bl1', 'nb_dm_l02_s1_p00_b1', 'Block 1', 1, 1) on conflict (id) do update set name = excluded.name;
insert into words (id, block_id, sort, term, level, pos, ipa, def_en, meaning_vi, meaning_zh, meaning_es, quiz_vi, freq) values
  ('nb_dm_l02_s1_p00_b1_bl1_w1', 'nb_dm_l02_s1_p00_b1_bl1', 1, 'ad account', 'B1', 'Noun phrase', '', 'An account used to create and pay for online ads.', 'tài khoản quảng cáo', '广告账户', 'cuenta publicitaria', 'tài khoản quảng cáo', 'common'),
  ('nb_dm_l02_s1_p00_b1_bl1_w2', 'nb_dm_l02_s1_p00_b1_bl1', 2, 'Business Manager', 'B2', 'Noun phrase', '', 'Meta''s tool for managing pages, ad accounts and team access in one place.', 'trình quản lý doanh nghiệp (Meta)', '商务管理平台', 'administrador comercial', 'trình quản lý doanh nghiệp', 'common'),
  ('nb_dm_l02_s1_p00_b1_bl1_w3', 'nb_dm_l02_s1_p00_b1_bl1', 3, 'Official Account (OA)', 'B2', 'Noun phrase', '', 'A verified business account on Zalo used to chat with and message customers.', 'tài khoản chính thức (Zalo OA)', '官方账号', 'cuenta oficial', 'tài khoản chính thức', 'common'),
  ('nb_dm_l02_s1_p00_b1_bl1_w4', 'nb_dm_l02_s1_p00_b1_bl1', 4, 'property', 'B2', 'Noun', '/ˈprɒpəti/', 'In Google Analytics, one report space for one website or app.', 'tài sản (cuốn sổ báo cáo trong GA4)', '媒体资源', 'propiedad', 'tài sản', 'common'),
  ('nb_dm_l02_s1_p00_b1_bl1_w5', 'nb_dm_l02_s1_p00_b1_bl1', 5, 'data stream', 'B2', 'Noun phrase', '', 'A source that sends visitor data from a website or app into Analytics.', 'luồng dữ liệu', '数据流', 'flujo de datos', 'luồng dữ liệu', 'common'),
  ('nb_dm_l02_s1_p00_b1_bl1_w6', 'nb_dm_l02_s1_p00_b1_bl1', 6, 'measurement ID', 'B2', 'Noun phrase', '', 'The code starting with G- that links a website to a GA4 property.', 'mã đo lường (G-...)', '衡量 ID', 'ID de medición', 'mã đo lường', 'common'),
  ('nb_dm_l02_s1_p00_b1_bl1_w7', 'nb_dm_l02_s1_p00_b1_bl1', 7, 'tag', 'B1', 'Noun', '/tæɡ/', 'A small piece of code added to a web page to collect data.', 'thẻ (đoạn mã theo dõi)', '代码标签', 'etiqueta', 'thẻ', 'common'),
  ('nb_dm_l02_s1_p00_b1_bl1_w8', 'nb_dm_l02_s1_p00_b1_bl1', 8, 'dashboard', 'B1', 'Noun', '/ˈdæʃbɔːd/', 'A screen that shows the main numbers and charts at a glance.', 'bảng tổng hợp số liệu', '仪表板', 'panel de control', 'bảng tổng hợp số liệu', 'common'),
  ('nb_dm_l02_s1_p00_b1_bl1_w9', 'nb_dm_l02_s1_p00_b1_bl1', 9, 'real-time report', 'B2', 'Noun phrase', '', 'A report that shows what visitors are doing on a site right now.', 'báo cáo thời gian thực', '实时报告', 'informe en tiempo real', 'báo cáo thời gian thực', 'common'),
  ('nb_dm_l02_s1_p00_b1_bl1_w10', 'nb_dm_l02_s1_p00_b1_bl1', 10, 'pixel', 'B2', 'Noun', '/ˈpɪksəl/', 'Tracking code from an ad platform that records what visitors do after clicking an ad.', 'pixel theo dõi (mã đo của nền tảng quảng cáo)', '像素代码', 'píxel de seguimiento', 'pixel theo dõi', 'common')
  on conflict (id) do update set term = excluded.term, level = excluded.level, pos = excluded.pos, ipa = excluded.ipa, def_en = excluded.def_en,
    meaning_vi = excluded.meaning_vi, meaning_zh = excluded.meaning_zh, meaning_es = excluded.meaning_es, quiz_vi = excluded.quiz_vi;
-- Module 01
insert into pages (id, section_id, name, sort, name_en) values ('nb_dm_l02_s1_p01', 'nb_dm_l02_s1', '🧭 01 — Tổng quan & hành trình khách hàng', 2, '01 — Overview & customer journey') on conflict (id) do update set name = excluded.name, sort = excluded.sort, name_en = excluded.name_en;
insert into batches (id, page_id, name, sort, created_at, name_en) values ('nb_dm_l02_s1_p01_b1', 'nb_dm_l02_s1_p01', 'Từ vựng', 1, 1791100000000, 'Vocabulary') on conflict (id) do update set name = excluded.name;
insert into blocks (id, batch_id, name, global_index, sort) values ('nb_dm_l02_s1_p01_b1_bl1', 'nb_dm_l02_s1_p01_b1', 'Block 1', 2, 1) on conflict (id) do update set name = excluded.name;
insert into words (id, block_id, sort, term, level, pos, ipa, def_en, meaning_vi, meaning_zh, meaning_es, quiz_vi, freq) values
  ('nb_dm_l02_s1_p01_b1_bl1_w1', 'nb_dm_l02_s1_p01_b1_bl1', 1, 'digital marketing', 'B1', 'Noun phrase', '', 'Promoting products or services using the internet and digital devices.', 'tiếp thị kỹ thuật số', '数字营销', 'marketing digital', 'tiếp thị kỹ thuật số', 'common'),
  ('nb_dm_l02_s1_p01_b1_bl1_w2', 'nb_dm_l02_s1_p01_b1_bl1', 2, 'customer journey', 'B2', 'Noun phrase', '', 'All the steps a customer goes through from first hearing about a product to buying it and after.', 'hành trình khách hàng', '客户旅程', 'recorrido del cliente', 'hành trình khách hàng', 'common'),
  ('nb_dm_l02_s1_p01_b1_bl1_w3', 'nb_dm_l02_s1_p01_b1_bl1', 3, 'touchpoint', 'B2', 'Noun', '/ˈtʌtʃpɔɪnt/', 'Any moment where a customer comes into contact with a brand.', 'điểm chạm', '接触点', 'punto de contacto', 'điểm chạm', 'common'),
  ('nb_dm_l02_s1_p01_b1_bl1_w4', 'nb_dm_l02_s1_p01_b1_bl1', 4, 'channel', 'B1', 'Noun', '/ˈtʃænəl/', 'A route used to reach customers, such as Facebook, Zalo or email.', 'kênh', '渠道', 'canal', 'kênh', 'common'),
  ('nb_dm_l02_s1_p01_b1_bl1_w5', 'nb_dm_l02_s1_p01_b1_bl1', 5, 'target audience', 'B1', 'Noun phrase', '', 'The specific group of people a business wants to reach.', 'khách hàng mục tiêu', '目标受众', 'público objetivo', 'khách hàng mục tiêu', 'common'),
  ('nb_dm_l02_s1_p01_b1_bl1_w6', 'nb_dm_l02_s1_p01_b1_bl1', 6, 'brand awareness', 'B2', 'Noun phrase', '', 'How well people know and recognise a brand.', 'mức độ nhận biết thương hiệu', '品牌知名度', 'reconocimiento de marca', 'mức độ nhận biết thương hiệu', 'common'),
  ('nb_dm_l02_s1_p01_b1_bl1_w7', 'nb_dm_l02_s1_p01_b1_bl1', 7, 'word of mouth', 'B2', 'Noun phrase', '', 'When people tell others about a product from their own experience.', 'truyền miệng', '口碑', 'boca a boca', 'truyền miệng', 'common'),
  ('nb_dm_l02_s1_p01_b1_bl1_w8', 'nb_dm_l02_s1_p01_b1_bl1', 8, 'price comparison', 'B1', 'Noun phrase', '', 'Checking the price of the same product in several shops before buying.', 'so sánh giá', '比价', 'comparación de precios', 'so sánh giá', 'common'),
  ('nb_dm_l02_s1_p01_b1_bl1_w9', 'nb_dm_l02_s1_p01_b1_bl1', 9, 'decision-making', 'B2', 'Noun', '/dɪˈsɪʒən ˌmeɪkɪŋ/', 'The process of choosing what to buy or do.', 'việc ra quyết định', '决策', 'toma de decisiones', 'việc ra quyết định', 'common'),
  ('nb_dm_l02_s1_p01_b1_bl1_w10', 'nb_dm_l02_s1_p01_b1_bl1', 10, 'online presence', 'B2', 'Noun phrase', '', 'How visible a business is on the internet.', 'sự hiện diện trực tuyến', '线上存在感', 'presencia en línea', 'sự hiện diện trực tuyến', 'common')
  on conflict (id) do update set term = excluded.term, level = excluded.level, pos = excluded.pos, ipa = excluded.ipa, def_en = excluded.def_en,
    meaning_vi = excluded.meaning_vi, meaning_zh = excluded.meaning_zh, meaning_es = excluded.meaning_es, quiz_vi = excluded.quiz_vi;
-- Module 02
insert into pages (id, section_id, name, sort, name_en) values ('nb_dm_l02_s1_p02', 'nb_dm_l02_s1', '🔻 02 — Phễu bán hàng (Funnel)', 3, '02 — Marketing funnel') on conflict (id) do update set name = excluded.name, sort = excluded.sort, name_en = excluded.name_en;
insert into batches (id, page_id, name, sort, created_at, name_en) values ('nb_dm_l02_s1_p02_b1', 'nb_dm_l02_s1_p02', 'Từ vựng', 1, 1791100000000, 'Vocabulary') on conflict (id) do update set name = excluded.name;
insert into blocks (id, batch_id, name, global_index, sort) values ('nb_dm_l02_s1_p02_b1_bl1', 'nb_dm_l02_s1_p02_b1', 'Block 1', 3, 1) on conflict (id) do update set name = excluded.name;
insert into words (id, block_id, sort, term, level, pos, ipa, def_en, meaning_vi, meaning_zh, meaning_es, quiz_vi, freq) values
  ('nb_dm_l02_s1_p02_b1_bl1_w1', 'nb_dm_l02_s1_p02_b1_bl1', 1, 'funnel', 'B2', 'Noun', '/ˈfʌnəl/', 'A model of the steps from first seeing a brand to buying and buying again.', 'phễu bán hàng', '营销漏斗', 'embudo de ventas', 'phễu bán hàng', 'common'),
  ('nb_dm_l02_s1_p02_b1_bl1_w2', 'nb_dm_l02_s1_p02_b1_bl1', 2, 'awareness', 'B2', 'Noun', '/əˈweənəs/', 'The first stage, when people first learn that a brand exists.', 'giai đoạn nhận biết', '认知阶段', 'reconocimiento', 'giai đoạn nhận biết', 'common'),
  ('nb_dm_l02_s1_p02_b1_bl1_w3', 'nb_dm_l02_s1_p02_b1_bl1', 3, 'consideration', 'B2', 'Noun', '/kənˌsɪdəˈreɪʃən/', 'The stage when people compare options and think about buying.', 'giai đoạn cân nhắc', '考虑阶段', 'consideración', 'giai đoạn cân nhắc', 'common'),
  ('nb_dm_l02_s1_p02_b1_bl1_w4', 'nb_dm_l02_s1_p02_b1_bl1', 4, 'conversion', 'B2', 'Noun', '/kənˈvɜːʃən/', 'When a person takes the action you want, such as buying or signing up.', 'chuyển đổi (khách làm hành động mong muốn)', '转化', 'conversión', 'chuyển đổi', 'common'),
  ('nb_dm_l02_s1_p02_b1_bl1_w5', 'nb_dm_l02_s1_p02_b1_bl1', 5, 'retention', 'C1', 'Noun', '/rɪˈtenʃən/', 'Keeping existing customers so they buy again.', 'giữ chân khách hàng', '客户留存', 'retención', 'giữ chân khách hàng', 'common'),
  ('nb_dm_l02_s1_p02_b1_bl1_w6', 'nb_dm_l02_s1_p02_b1_bl1', 6, 'lead', 'B2', 'Noun', '/liːd/', 'A person who has shown interest and left contact details.', 'khách hàng tiềm năng (đã để lại thông tin)', '潜在客户', 'cliente potencial', 'khách hàng tiềm năng', 'common'),
  ('nb_dm_l02_s1_p02_b1_bl1_w7', 'nb_dm_l02_s1_p02_b1_bl1', 7, 'drop-off', 'C1', 'Noun', '/ˈdrɒp ɒf/', 'The point where many people leave the funnel without continuing.', 'chỗ rớt khách', '流失点', 'abandono', 'chỗ rớt khách', 'common'),
  ('nb_dm_l02_s1_p02_b1_bl1_w8', 'nb_dm_l02_s1_p02_b1_bl1', 8, 'landing page', 'B2', 'Noun phrase', '', 'The web page people arrive at after clicking an ad or link.', 'trang đích', '落地页', 'página de destino', 'trang đích', 'common'),
  ('nb_dm_l02_s1_p02_b1_bl1_w9', 'nb_dm_l02_s1_p02_b1_bl1', 9, 'call to action (CTA)', 'B2', 'Noun phrase', '', 'A short message or button telling people what to do next, like ''Buy now''.', 'lời kêu gọi hành động', '行动号召', 'llamada a la acción', 'lời kêu gọi hành động', 'common'),
  ('nb_dm_l02_s1_p02_b1_bl1_w10', 'nb_dm_l02_s1_p02_b1_bl1', 10, 'TOFU / MOFU / BOFU', 'C1', 'Abbreviation', '', 'Top, middle and bottom of the funnel.', 'đầu / giữa / đáy phễu', '漏斗顶部/中部/底部', 'parte alta / media / baja del embudo', 'đầu / giữa / đáy phễu', 'common')
  on conflict (id) do update set term = excluded.term, level = excluded.level, pos = excluded.pos, ipa = excluded.ipa, def_en = excluded.def_en,
    meaning_vi = excluded.meaning_vi, meaning_zh = excluded.meaning_zh, meaning_es = excluded.meaning_es, quiz_vi = excluded.quiz_vi;
-- Module 03
insert into pages (id, section_id, name, sort, name_en) values ('nb_dm_l02_s1_p03', 'nb_dm_l02_s1', '👤 03 — Chân dung khách hàng (Persona)', 4, '03 — Buyer persona') on conflict (id) do update set name = excluded.name, sort = excluded.sort, name_en = excluded.name_en;
insert into batches (id, page_id, name, sort, created_at, name_en) values ('nb_dm_l02_s1_p03_b1', 'nb_dm_l02_s1_p03', 'Từ vựng', 1, 1791100000000, 'Vocabulary') on conflict (id) do update set name = excluded.name;
insert into blocks (id, batch_id, name, global_index, sort) values ('nb_dm_l02_s1_p03_b1_bl1', 'nb_dm_l02_s1_p03_b1', 'Block 1', 4, 1) on conflict (id) do update set name = excluded.name;
insert into words (id, block_id, sort, term, level, pos, ipa, def_en, meaning_vi, meaning_zh, meaning_es, quiz_vi, freq) values
  ('nb_dm_l02_s1_p03_b1_bl1_w1', 'nb_dm_l02_s1_p03_b1_bl1', 1, 'buyer persona', 'B2', 'Noun phrase', '', 'A detailed profile of a typical customer, based on real data.', 'chân dung khách hàng', '买家画像', 'buyer persona', 'chân dung khách hàng', 'common'),
  ('nb_dm_l02_s1_p03_b1_bl1_w2', 'nb_dm_l02_s1_p03_b1_bl1', 2, 'pain point', 'B2', 'Noun phrase', '', 'A problem or frustration a customer wants to solve.', 'nỗi đau (vấn đề khách đang gặp)', '痛点', 'punto de dolor', 'nỗi đau', 'common'),
  ('nb_dm_l02_s1_p03_b1_bl1_w3', 'nb_dm_l02_s1_p03_b1_bl1', 3, 'demographics', 'B2', 'Noun', '/ˌdeməˈɡræfɪks/', 'Facts about people such as age, gender, income and location.', 'đặc điểm nhân khẩu học (tuổi, giới tính, thu nhập…)', '人口统计特征', 'datos demográficos', 'đặc điểm nhân khẩu học', 'common'),
  ('nb_dm_l02_s1_p03_b1_bl1_w4', 'nb_dm_l02_s1_p03_b1_bl1', 4, 'motivation', 'B1', 'Noun', '/ˌməʊtɪˈveɪʃən/', 'The reason that makes someone want to buy.', 'động lực', '动机', 'motivación', 'động lực', 'common'),
  ('nb_dm_l02_s1_p03_b1_bl1_w5', 'nb_dm_l02_s1_p03_b1_bl1', 5, 'objection', 'B2', 'Noun', '/əbˈdʒekʃən/', 'A reason a customer gives for not buying yet.', 'lý do còn ngần ngại', '顾虑', 'objeción', 'lý do còn ngần ngại', 'common'),
  ('nb_dm_l02_s1_p03_b1_bl1_w6', 'nb_dm_l02_s1_p03_b1_bl1', 6, 'market research', 'B2', 'Noun phrase', '', 'Collecting information about customers and competitors.', 'nghiên cứu thị trường', '市场调研', 'investigación de mercado', 'nghiên cứu thị trường', 'common'),
  ('nb_dm_l02_s1_p03_b1_bl1_w7', 'nb_dm_l02_s1_p03_b1_bl1', 7, 'survey', 'B1', 'Noun', '/ˈsɜːveɪ/', 'A set of questions asked to many people to collect opinions.', 'khảo sát', '问卷调查', 'encuesta', 'khảo sát', 'common'),
  ('nb_dm_l02_s1_p03_b1_bl1_w8', 'nb_dm_l02_s1_p03_b1_bl1', 8, 'competitor', 'B1', 'Noun', '/kəmˈpetɪtə/', 'Another business that sells similar products.', 'đối thủ cạnh tranh', '竞争对手', 'competidor', 'đối thủ cạnh tranh', 'common'),
  ('nb_dm_l02_s1_p03_b1_bl1_w9', 'nb_dm_l02_s1_p03_b1_bl1', 9, 'assumption', 'B2', 'Noun', '/əˈsʌmpʃən/', 'Something you believe is true without proof.', 'giả định (đoán, chưa có bằng chứng)', '假设', 'suposición', 'giả định', 'common'),
  ('nb_dm_l02_s1_p03_b1_bl1_w10', 'nb_dm_l02_s1_p03_b1_bl1', 10, 'insight', 'B2', 'Noun', '/ˈɪnsaɪt/', 'A useful understanding about customers found from data.', 'điều nhận ra (từ dữ liệu)', '洞察', 'hallazgo', 'điều nhận ra', 'common')
  on conflict (id) do update set term = excluded.term, level = excluded.level, pos = excluded.pos, ipa = excluded.ipa, def_en = excluded.def_en,
    meaning_vi = excluded.meaning_vi, meaning_zh = excluded.meaning_zh, meaning_es = excluded.meaning_es, quiz_vi = excluded.quiz_vi;
-- Module 04
insert into pages (id, section_id, name, sort, name_en) values ('nb_dm_l02_s1_p04', 'nb_dm_l02_s1', '🗺️ 04 — Chọn nền tảng ở Việt Nam', 5, '04 — Vietnam platform ecosystem') on conflict (id) do update set name = excluded.name, sort = excluded.sort, name_en = excluded.name_en;
insert into batches (id, page_id, name, sort, created_at, name_en) values ('nb_dm_l02_s1_p04_b1', 'nb_dm_l02_s1_p04', 'Từ vựng', 1, 1791100000000, 'Vocabulary') on conflict (id) do update set name = excluded.name;
insert into blocks (id, batch_id, name, global_index, sort) values ('nb_dm_l02_s1_p04_b1_bl1', 'nb_dm_l02_s1_p04_b1', 'Block 1', 5, 1) on conflict (id) do update set name = excluded.name;
insert into words (id, block_id, sort, term, level, pos, ipa, def_en, meaning_vi, meaning_zh, meaning_es, quiz_vi, freq) values
  ('nb_dm_l02_s1_p04_b1_bl1_w1', 'nb_dm_l02_s1_p04_b1_bl1', 1, 'platform', 'B1', 'Noun', '/ˈplætfɔːm/', 'An online service where businesses reach users, such as TikTok or Shopee.', 'nền tảng', '平台', 'plataforma', 'nền tảng', 'common'),
  ('nb_dm_l02_s1_p04_b1_bl1_w2', 'nb_dm_l02_s1_p04_b1_bl1', 2, 'social media', 'B1', 'Noun phrase', '', 'Websites and apps where people share content and talk to each other.', 'mạng xã hội', '社交媒体', 'redes sociales', 'mạng xã hội', 'common'),
  ('nb_dm_l02_s1_p04_b1_bl1_w3', 'nb_dm_l02_s1_p04_b1_bl1', 3, 'e-commerce', 'B2', 'Noun', '/ˌiː ˈkɒmɜːs/', 'Buying and selling products online.', 'thương mại điện tử', '电子商务', 'comercio electrónico', 'thương mại điện tử', 'common'),
  ('nb_dm_l02_s1_p04_b1_bl1_w4', 'nb_dm_l02_s1_p04_b1_bl1', 4, 'marketplace', 'B2', 'Noun', '/ˈmɑːkɪtpleɪs/', 'A website where many sellers offer products, like Shopee or Lazada.', 'sàn thương mại điện tử', '电商平台', 'mercado en línea', 'sàn thương mại điện tử', 'common'),
  ('nb_dm_l02_s1_p04_b1_bl1_w5', 'nb_dm_l02_s1_p04_b1_bl1', 5, 'search engine', 'B1', 'Noun phrase', '', 'A website like Google that finds information when you type words.', 'công cụ tìm kiếm', '搜索引擎', 'motor de búsqueda', 'công cụ tìm kiếm', 'common'),
  ('nb_dm_l02_s1_p04_b1_bl1_w6', 'nb_dm_l02_s1_p04_b1_bl1', 6, 'user base', 'B2', 'Noun phrase', '', 'All the people who use a platform.', 'lượng người dùng', '用户群', 'base de usuarios', 'lượng người dùng', 'common'),
  ('nb_dm_l02_s1_p04_b1_bl1_w7', 'nb_dm_l02_s1_p04_b1_bl1', 7, 'search intent', 'C1', 'Noun phrase', '', 'What a person really wants when they search for something.', 'ý định tìm kiếm', '搜索意图', 'intención de búsqueda', 'ý định tìm kiếm', 'common'),
  ('nb_dm_l02_s1_p04_b1_bl1_w8', 'nb_dm_l02_s1_p04_b1_bl1', 8, 'channel mix', 'C1', 'Noun phrase', '', 'The combination of channels a business uses together.', 'tổ hợp kênh', '渠道组合', 'combinación de canales', 'tổ hợp kênh', 'common'),
  ('nb_dm_l02_s1_p04_b1_bl1_w9', 'nb_dm_l02_s1_p04_b1_bl1', 9, 'short-form video', 'B2', 'Noun phrase', '', 'Short videos, usually under one minute, like TikTok or Reels.', 'video ngắn', '短视频', 'vídeo corto', 'video ngắn', 'common'),
  ('nb_dm_l02_s1_p04_b1_bl1_w10', 'nb_dm_l02_s1_p04_b1_bl1', 10, 'resources', 'B1', 'Noun', '/rɪˈzɔːsɪz/', 'The time, money and people available to do the work.', 'nguồn lực', '资源', 'recursos', 'nguồn lực', 'common')
  on conflict (id) do update set term = excluded.term, level = excluded.level, pos = excluded.pos, ipa = excluded.ipa, def_en = excluded.def_en,
    meaning_vi = excluded.meaning_vi, meaning_zh = excluded.meaning_zh, meaning_es = excluded.meaning_es, quiz_vi = excluded.quiz_vi;
-- Module 05
insert into pages (id, section_id, name, sort, name_en) values ('nb_dm_l02_s1_p05', 'nb_dm_l02_s1', '📘 05 — Quảng cáo Facebook & Instagram', 6, '05 — Facebook & Instagram Ads') on conflict (id) do update set name = excluded.name, sort = excluded.sort, name_en = excluded.name_en;
insert into batches (id, page_id, name, sort, created_at, name_en) values ('nb_dm_l02_s1_p05_b1', 'nb_dm_l02_s1_p05', 'Từ vựng', 1, 1791100000000, 'Vocabulary') on conflict (id) do update set name = excluded.name;
insert into blocks (id, batch_id, name, global_index, sort) values ('nb_dm_l02_s1_p05_b1_bl1', 'nb_dm_l02_s1_p05_b1', 'Block 1', 6, 1) on conflict (id) do update set name = excluded.name;
insert into words (id, block_id, sort, term, level, pos, ipa, def_en, meaning_vi, meaning_zh, meaning_es, quiz_vi, freq) values
  ('nb_dm_l02_s1_p05_b1_bl1_w1', 'nb_dm_l02_s1_p05_b1_bl1', 1, 'campaign', 'B1', 'Noun', '/kæmˈpeɪn/', 'A planned set of ads with one main goal.', 'chiến dịch', '广告系列', 'campaña', 'chiến dịch', 'common'),
  ('nb_dm_l02_s1_p05_b1_bl1_w2', 'nb_dm_l02_s1_p05_b1_bl1', 2, 'ad set', 'B2', 'Noun phrase', '', 'The level that controls audience, budget and schedule for a group of ads.', 'nhóm quảng cáo', '广告组', 'conjunto de anuncios', 'nhóm quảng cáo', 'common'),
  ('nb_dm_l02_s1_p05_b1_bl1_w3', 'nb_dm_l02_s1_p05_b1_bl1', 3, 'objective', 'B2', 'Noun', '/əbˈdʒektɪv/', 'The goal you choose for a campaign, such as traffic or sales.', 'mục tiêu (của chiến dịch)', '广告目标', 'objetivo', 'mục tiêu', 'common'),
  ('nb_dm_l02_s1_p05_b1_bl1_w4', 'nb_dm_l02_s1_p05_b1_bl1', 4, 'targeting', 'B2', 'Noun', '/ˈtɑːɡɪtɪŋ/', 'Choosing which people will see your ads.', 'nhắm chọn đối tượng', '定向', 'segmentación', 'nhắm chọn đối tượng', 'common'),
  ('nb_dm_l02_s1_p05_b1_bl1_w5', 'nb_dm_l02_s1_p05_b1_bl1', 5, 'lookalike audience', 'C1', 'Noun phrase', '', 'New people who are similar to your existing customers.', 'đối tượng tương tự', '类似受众', 'público similar', 'đối tượng tương tự', 'common'),
  ('nb_dm_l02_s1_p05_b1_bl1_w6', 'nb_dm_l02_s1_p05_b1_bl1', 6, 'custom audience', 'C1', 'Noun phrase', '', 'People who already interacted with your business, like visitors or buyers.', 'đối tượng tuỳ chỉnh (người đã tương tác)', '自定义受众', 'público personalizado', 'đối tượng tuỳ chỉnh', 'common'),
  ('nb_dm_l02_s1_p05_b1_bl1_w7', 'nb_dm_l02_s1_p05_b1_bl1', 7, 'daily budget', 'B1', 'Noun phrase', '', 'The average amount of money you spend on ads each day.', 'ngân sách mỗi ngày', '每日预算', 'presupuesto diario', 'ngân sách mỗi ngày', 'common'),
  ('nb_dm_l02_s1_p05_b1_bl1_w8', 'nb_dm_l02_s1_p05_b1_bl1', 8, 'placement', 'B2', 'Noun', '/ˈpleɪsmənt/', 'Where your ad appears, such as Feed, Stories or Reels.', 'vị trí hiển thị quảng cáo', '版位', 'ubicación', 'vị trí hiển thị quảng cáo', 'common'),
  ('nb_dm_l02_s1_p05_b1_bl1_w9', 'nb_dm_l02_s1_p05_b1_bl1', 9, 'ad creative', 'B2', 'Noun phrase', '', 'The image, video and text that make up an ad.', 'nội dung quảng cáo (hình, video, chữ)', '广告创意', 'creatividad publicitaria', 'nội dung quảng cáo', 'common'),
  ('nb_dm_l02_s1_p05_b1_bl1_w10', 'nb_dm_l02_s1_p05_b1_bl1', 10, 'reach', 'B1', 'Noun', '/riːtʃ/', 'The number of different people who saw your ad.', 'lượt tiếp cận', '覆盖人数', 'alcance', 'lượt tiếp cận', 'common')
  on conflict (id) do update set term = excluded.term, level = excluded.level, pos = excluded.pos, ipa = excluded.ipa, def_en = excluded.def_en,
    meaning_vi = excluded.meaning_vi, meaning_zh = excluded.meaning_zh, meaning_es = excluded.meaning_es, quiz_vi = excluded.quiz_vi;
-- Module 06
insert into pages (id, section_id, name, sort, name_en) values ('nb_dm_l02_s1_p06', 'nb_dm_l02_s1', '🎵 06 — Quảng cáo TikTok, Google & Zalo', 7, '06 — TikTok, Google & Zalo Ads') on conflict (id) do update set name = excluded.name, sort = excluded.sort, name_en = excluded.name_en;
insert into batches (id, page_id, name, sort, created_at, name_en) values ('nb_dm_l02_s1_p06_b1', 'nb_dm_l02_s1_p06', 'Từ vựng', 1, 1791100000000, 'Vocabulary') on conflict (id) do update set name = excluded.name;
insert into blocks (id, batch_id, name, global_index, sort) values ('nb_dm_l02_s1_p06_b1_bl1', 'nb_dm_l02_s1_p06_b1', 'Block 1', 7, 1) on conflict (id) do update set name = excluded.name;
insert into words (id, block_id, sort, term, level, pos, ipa, def_en, meaning_vi, meaning_zh, meaning_es, quiz_vi, freq) values
  ('nb_dm_l02_s1_p06_b1_bl1_w1', 'nb_dm_l02_s1_p06_b1_bl1', 1, 'keyword', 'B1', 'Noun', '/ˈkiːwɜːd/', 'A word or phrase people type into a search engine.', 'từ khoá', '关键词', 'palabra clave', 'từ khoá', 'common'),
  ('nb_dm_l02_s1_p06_b1_bl1_w2', 'nb_dm_l02_s1_p06_b1_bl1', 2, 'search ads', 'B2', 'Noun phrase', '', 'Ads that appear when people search for certain words on Google.', 'quảng cáo tìm kiếm', '搜索广告', 'anuncios de búsqueda', 'quảng cáo tìm kiếm', 'common'),
  ('nb_dm_l02_s1_p06_b1_bl1_w3', 'nb_dm_l02_s1_p06_b1_bl1', 3, 'display ads', 'B2', 'Noun phrase', '', 'Image or banner ads shown on websites and apps.', 'quảng cáo hiển thị (banner)', '展示广告', 'anuncios de display', 'quảng cáo hiển thị', 'common'),
  ('nb_dm_l02_s1_p06_b1_bl1_w4', 'nb_dm_l02_s1_p06_b1_bl1', 4, 'bid', 'B2', 'Noun', '/bɪd/', 'The most you are willing to pay for a click or result.', 'giá thầu', '出价', 'puja', 'giá thầu', 'common'),
  ('nb_dm_l02_s1_p06_b1_bl1_w5', 'nb_dm_l02_s1_p06_b1_bl1', 5, 'negative keyword', 'C1', 'Noun phrase', '', 'A word you add so your ad does NOT show for searches containing it.', 'từ khoá phủ định', '否定关键词', 'palabra clave negativa', 'từ khoá phủ định', 'common'),
  ('nb_dm_l02_s1_p06_b1_bl1_w6', 'nb_dm_l02_s1_p06_b1_bl1', 6, 'in-feed ad', 'B2', 'Noun phrase', '', 'An ad that appears between normal videos or posts in a feed.', 'quảng cáo xen giữa bảng tin', '信息流广告', 'anuncio en el feed', 'quảng cáo xen giữa bảng tin', 'common'),
  ('nb_dm_l02_s1_p06_b1_bl1_w7', 'nb_dm_l02_s1_p06_b1_bl1', 7, 'hook', 'B2', 'Noun', '/hʊk/', 'The first seconds of a video that grab attention.', 'câu mở đầu giữ chân người xem', '开头钩子', 'gancho', 'câu mở đầu giữ chân người xem', 'common'),
  ('nb_dm_l02_s1_p06_b1_bl1_w8', 'nb_dm_l02_s1_p06_b1_bl1', 8, 'Performance Max', 'C1', 'Noun phrase', '', 'A Google Ads campaign type that runs across all Google channels automatically.', 'chiến dịch tối đa hoá hiệu suất (Google)', '效果最大化广告系列', 'Máximo rendimiento', 'chiến dịch tối đa hoá hiệu suất', 'common'),
  ('nb_dm_l02_s1_p06_b1_bl1_w9', 'nb_dm_l02_s1_p06_b1_bl1', 9, 'message ads', 'B2', 'Noun phrase', '', 'Ads that open a chat with the business when clicked.', 'quảng cáo mở tin nhắn', '消息广告', 'anuncios de mensajes', 'quảng cáo mở tin nhắn', 'common'),
  ('nb_dm_l02_s1_p06_b1_bl1_w10', 'nb_dm_l02_s1_p06_b1_bl1', 10, 'ad auction', 'C1', 'Noun phrase', '', 'The process a platform uses to decide which ads to show and at what price.', 'phiên đấu giá quảng cáo', '广告竞价', 'subasta de anuncios', 'phiên đấu giá quảng cáo', 'common')
  on conflict (id) do update set term = excluded.term, level = excluded.level, pos = excluded.pos, ipa = excluded.ipa, def_en = excluded.def_en,
    meaning_vi = excluded.meaning_vi, meaning_zh = excluded.meaning_zh, meaning_es = excluded.meaning_es, quiz_vi = excluded.quiz_vi;
-- Module 07
insert into pages (id, section_id, name, sort, name_en) values ('nb_dm_l02_s1_p07', 'nb_dm_l02_s1', '🔍 07 — SEO & viết bài cho website', 8, '07 — SEO & website content') on conflict (id) do update set name = excluded.name, sort = excluded.sort, name_en = excluded.name_en;
insert into batches (id, page_id, name, sort, created_at, name_en) values ('nb_dm_l02_s1_p07_b1', 'nb_dm_l02_s1_p07', 'Từ vựng', 1, 1791100000000, 'Vocabulary') on conflict (id) do update set name = excluded.name;
insert into blocks (id, batch_id, name, global_index, sort) values ('nb_dm_l02_s1_p07_b1_bl1', 'nb_dm_l02_s1_p07_b1', 'Block 1', 8, 1) on conflict (id) do update set name = excluded.name;
insert into words (id, block_id, sort, term, level, pos, ipa, def_en, meaning_vi, meaning_zh, meaning_es, quiz_vi, freq) values
  ('nb_dm_l02_s1_p07_b1_bl1_w1', 'nb_dm_l02_s1_p07_b1_bl1', 1, 'SEO', 'B2', 'Abbreviation', '/ˌes iː ˈəʊ/', 'Search Engine Optimisation: improving a site so it ranks higher in free search results.', 'tối ưu hoá công cụ tìm kiếm', '搜索引擎优化', 'posicionamiento en buscadores', 'tối ưu hoá công cụ tìm kiếm', 'common'),
  ('nb_dm_l02_s1_p07_b1_bl1_w2', 'nb_dm_l02_s1_p07_b1_bl1', 2, 'organic traffic', 'B2', 'Noun phrase', '', 'Visitors who come from free search results, not from ads.', 'lượt truy cập tự nhiên (không trả tiền)', '自然流量', 'tráfico orgánico', 'lượt truy cập tự nhiên', 'common'),
  ('nb_dm_l02_s1_p07_b1_bl1_w3', 'nb_dm_l02_s1_p07_b1_bl1', 3, 'on-page SEO', 'C1', 'Noun phrase', '', 'SEO work done on the page itself, like titles, headings and content.', 'SEO trên trang', '页面内优化', 'SEO on-page', 'SEO trên trang', 'common'),
  ('nb_dm_l02_s1_p07_b1_bl1_w4', 'nb_dm_l02_s1_p07_b1_bl1', 4, 'meta description', 'C1', 'Noun phrase', '', 'The short summary of a page shown under its title in search results.', 'đoạn mô tả hiện trên Google', '元描述', 'meta descripción', 'đoạn mô tả hiện trên Google', 'common'),
  ('nb_dm_l02_s1_p07_b1_bl1_w5', 'nb_dm_l02_s1_p07_b1_bl1', 5, 'ranking', 'B2', 'Noun', '/ˈræŋkɪŋ/', 'The position of a page in search results.', 'thứ hạng', '排名', 'posicionamiento', 'thứ hạng', 'common'),
  ('nb_dm_l02_s1_p07_b1_bl1_w6', 'nb_dm_l02_s1_p07_b1_bl1', 6, 'backlink', 'C1', 'Noun', '/ˈbæklɪŋk/', 'A link from another website to your website.', 'liên kết từ trang khác trỏ về', '外链', 'enlace entrante', 'liên kết từ trang khác trỏ về', 'common'),
  ('nb_dm_l02_s1_p07_b1_bl1_w7', 'nb_dm_l02_s1_p07_b1_bl1', 7, 'content pillar', 'C1', 'Noun phrase', '', 'A main topic that many related posts are built around.', 'trụ cột nội dung (chủ đề chính)', '内容支柱', 'pilar de contenido', 'trụ cột nội dung', 'common'),
  ('nb_dm_l02_s1_p07_b1_bl1_w8', 'nb_dm_l02_s1_p07_b1_bl1', 8, 'long-tail keyword', 'C1', 'Noun phrase', '', 'A longer, more specific search phrase with fewer but better searches.', 'từ khoá dài (cụ thể)', '长尾关键词', 'palabra clave de cola larga', 'từ khoá dài', 'common'),
  ('nb_dm_l02_s1_p07_b1_bl1_w9', 'nb_dm_l02_s1_p07_b1_bl1', 9, 'search volume', 'B2', 'Noun phrase', '', 'How many times people search for a keyword each month.', 'lượng tìm kiếm', '搜索量', 'volumen de búsqueda', 'lượng tìm kiếm', 'common'),
  ('nb_dm_l02_s1_p07_b1_bl1_w10', 'nb_dm_l02_s1_p07_b1_bl1', 10, 'blog post', 'B1', 'Noun phrase', '', 'An article published on a website''s blog.', 'bài viết blog', '博客文章', 'entrada de blog', 'bài viết blog', 'common')
  on conflict (id) do update set term = excluded.term, level = excluded.level, pos = excluded.pos, ipa = excluded.ipa, def_en = excluded.def_en,
    meaning_vi = excluded.meaning_vi, meaning_zh = excluded.meaning_zh, meaning_es = excluded.meaning_es, quiz_vi = excluded.quiz_vi;
-- Module 08
insert into pages (id, section_id, name, sort, name_en) values ('nb_dm_l02_s1_p08', 'nb_dm_l02_s1', '💬 08 — Xây kênh & cộng đồng', 9, '08 — Channels & community') on conflict (id) do update set name = excluded.name, sort = excluded.sort, name_en = excluded.name_en;
insert into batches (id, page_id, name, sort, created_at, name_en) values ('nb_dm_l02_s1_p08_b1', 'nb_dm_l02_s1_p08', 'Từ vựng', 1, 1791100000000, 'Vocabulary') on conflict (id) do update set name = excluded.name;
insert into blocks (id, batch_id, name, global_index, sort) values ('nb_dm_l02_s1_p08_b1_bl1', 'nb_dm_l02_s1_p08_b1', 'Block 1', 9, 1) on conflict (id) do update set name = excluded.name;
insert into words (id, block_id, sort, term, level, pos, ipa, def_en, meaning_vi, meaning_zh, meaning_es, quiz_vi, freq) values
  ('nb_dm_l02_s1_p08_b1_bl1_w1', 'nb_dm_l02_s1_p08_b1_bl1', 1, 'engagement', 'B2', 'Noun', '/ɪnˈɡeɪdʒmənt/', 'Likes, comments, shares and other ways people interact with content.', 'lượt tương tác', '互动', 'interacción', 'lượt tương tác', 'common'),
  ('nb_dm_l02_s1_p08_b1_bl1_w2', 'nb_dm_l02_s1_p08_b1_bl1', 2, 'community', 'B1', 'Noun', '/kəˈmjuːnəti/', 'A group of people who share an interest and talk with each other.', 'cộng đồng', '社群', 'comunidad', 'cộng đồng', 'common'),
  ('nb_dm_l02_s1_p08_b1_bl1_w3', 'nb_dm_l02_s1_p08_b1_bl1', 3, 'follower', 'B1', 'Noun', '/ˈfɒləʊə/', 'A person who chooses to see a page''s or account''s posts.', 'người theo dõi', '粉丝', 'seguidor', 'người theo dõi', 'common'),
  ('nb_dm_l02_s1_p08_b1_bl1_w4', 'nb_dm_l02_s1_p08_b1_bl1', 4, 'content calendar', 'B2', 'Noun phrase', '', 'A schedule showing what will be posted and when.', 'lịch nội dung', '内容日历', 'calendario de contenidos', 'lịch nội dung', 'common'),
  ('nb_dm_l02_s1_p08_b1_bl1_w5', 'nb_dm_l02_s1_p08_b1_bl1', 5, 'algorithm', 'B2', 'Noun', '/ˈælɡərɪðəm/', 'The rules a platform uses to decide which posts people see.', 'thuật toán', '算法', 'algoritmo', 'thuật toán', 'common'),
  ('nb_dm_l02_s1_p08_b1_bl1_w6', 'nb_dm_l02_s1_p08_b1_bl1', 6, 'user-generated content (UGC)', 'C1', 'Noun phrase', '', 'Content made by customers, such as reviews or photos.', 'nội dung do khách hàng tạo', '用户生成内容', 'contenido generado por usuarios', 'nội dung do khách hàng tạo', 'common'),
  ('nb_dm_l02_s1_p08_b1_bl1_w7', 'nb_dm_l02_s1_p08_b1_bl1', 7, 'broadcast message', 'B2', 'Noun phrase', '', 'One message sent to many followers at once, like on Zalo OA.', 'tin nhắn gửi hàng loạt', '群发消息', 'mensaje masivo', 'tin nhắn gửi hàng loạt', 'common'),
  ('nb_dm_l02_s1_p08_b1_bl1_w8', 'nb_dm_l02_s1_p08_b1_bl1', 8, 'moderator', 'B2', 'Noun', '/ˈmɒdəreɪtə/', 'A person who manages a group and keeps discussions friendly.', 'người kiểm duyệt nhóm', '版主', 'moderador', 'người kiểm duyệt nhóm', 'common'),
  ('nb_dm_l02_s1_p08_b1_bl1_w9', 'nb_dm_l02_s1_p08_b1_bl1', 9, 'posting frequency', 'B2', 'Noun phrase', '', 'How often an account publishes new posts.', 'tần suất đăng bài', '发布频率', 'frecuencia de publicación', 'tần suất đăng bài', 'common'),
  ('nb_dm_l02_s1_p08_b1_bl1_w10', 'nb_dm_l02_s1_p08_b1_bl1', 10, 'organic reach', 'C1', 'Noun phrase', '', 'The number of people who see a post without paid promotion.', 'lượt tiếp cận tự nhiên', '自然覆盖', 'alcance orgánico', 'lượt tiếp cận tự nhiên', 'common')
  on conflict (id) do update set term = excluded.term, level = excluded.level, pos = excluded.pos, ipa = excluded.ipa, def_en = excluded.def_en,
    meaning_vi = excluded.meaning_vi, meaning_zh = excluded.meaning_zh, meaning_es = excluded.meaning_es, quiz_vi = excluded.quiz_vi;
-- Module 09
insert into pages (id, section_id, name, sort, name_en) values ('nb_dm_l02_s1_p09', 'nb_dm_l02_s1', '📊 09 — Đo lường & phân tích', 10, '09 — Measurement & analytics') on conflict (id) do update set name = excluded.name, sort = excluded.sort, name_en = excluded.name_en;
insert into batches (id, page_id, name, sort, created_at, name_en) values ('nb_dm_l02_s1_p09_b1', 'nb_dm_l02_s1_p09', 'Từ vựng', 1, 1791100000000, 'Vocabulary') on conflict (id) do update set name = excluded.name;
insert into blocks (id, batch_id, name, global_index, sort) values ('nb_dm_l02_s1_p09_b1_bl1', 'nb_dm_l02_s1_p09_b1', 'Block 1', 10, 1) on conflict (id) do update set name = excluded.name;
insert into words (id, block_id, sort, term, level, pos, ipa, def_en, meaning_vi, meaning_zh, meaning_es, quiz_vi, freq) values
  ('nb_dm_l02_s1_p09_b1_bl1_w1', 'nb_dm_l02_s1_p09_b1_bl1', 1, 'KPI', 'B2', 'Abbreviation', '/ˌkeɪ piː ˈaɪ/', 'Key Performance Indicator: the main number used to judge success.', 'chỉ số đo hiệu quả chính', '关键绩效指标', 'indicador clave de rendimiento', 'chỉ số đo hiệu quả chính', 'common'),
  ('nb_dm_l02_s1_p09_b1_bl1_w2', 'nb_dm_l02_s1_p09_b1_bl1', 2, 'impression', 'B2', 'Noun', '/ɪmˈpreʃən/', 'One time an ad is shown on a screen.', 'lượt hiển thị', '展示次数', 'impresión', 'lượt hiển thị', 'common'),
  ('nb_dm_l02_s1_p09_b1_bl1_w3', 'nb_dm_l02_s1_p09_b1_bl1', 3, 'CTR', 'C1', 'Abbreviation', '/ˌsiː tiː ˈɑː/', 'Click-through rate: clicks divided by impressions.', 'tỉ lệ nhấp', '点击率', 'tasa de clics', 'tỉ lệ nhấp', 'common'),
  ('nb_dm_l02_s1_p09_b1_bl1_w4', 'nb_dm_l02_s1_p09_b1_bl1', 4, 'CPC', 'C1', 'Abbreviation', '/ˌsiː piː ˈsiː/', 'Cost per click: money spent divided by clicks.', 'chi phí mỗi lượt nhấp', '每次点击费用', 'coste por clic', 'chi phí mỗi lượt nhấp', 'common'),
  ('nb_dm_l02_s1_p09_b1_bl1_w5', 'nb_dm_l02_s1_p09_b1_bl1', 5, 'CPA', 'C1', 'Abbreviation', '/ˌsiː piː ˈeɪ/', 'Cost per action: money spent divided by conversions.', 'chi phí mỗi chuyển đổi', '每次转化费用', 'coste por adquisición', 'chi phí mỗi chuyển đổi', 'common'),
  ('nb_dm_l02_s1_p09_b1_bl1_w6', 'nb_dm_l02_s1_p09_b1_bl1', 6, 'ROAS', 'C1', 'Abbreviation', '/ˈrəʊæs/', 'Return on ad spend: revenue from ads divided by ad cost.', 'doanh thu trên chi phí quảng cáo', '广告支出回报率', 'retorno de la inversión publicitaria', 'doanh thu trên chi phí quảng cáo', 'common'),
  ('nb_dm_l02_s1_p09_b1_bl1_w7', 'nb_dm_l02_s1_p09_b1_bl1', 7, 'conversion rate', 'B2', 'Noun phrase', '', 'The percentage of visitors who take the desired action.', 'tỉ lệ chuyển đổi', '转化率', 'tasa de conversión', 'tỉ lệ chuyển đổi', 'common'),
  ('nb_dm_l02_s1_p09_b1_bl1_w8', 'nb_dm_l02_s1_p09_b1_bl1', 8, 'UTM parameter', 'C1', 'Noun phrase', '', 'Tags added to a link to show which source and campaign a visitor came from.', 'tham số UTM (gắn vào link để biết khách từ đâu tới)', 'UTM 参数', 'parámetro UTM', 'tham số UTM', 'common'),
  ('nb_dm_l02_s1_p09_b1_bl1_w9', 'nb_dm_l02_s1_p09_b1_bl1', 9, 'bounce rate', 'C1', 'Noun phrase', '', 'The percentage of visitors who leave after seeing only one page.', 'tỉ lệ thoát', '跳出率', 'tasa de rebote', 'tỉ lệ thoát', 'common'),
  ('nb_dm_l02_s1_p09_b1_bl1_w10', 'nb_dm_l02_s1_p09_b1_bl1', 10, 'event', 'B1', 'Noun', '/ɪˈvent/', 'In GA4, one action a visitor takes, such as a click or a purchase.', 'sự kiện (hành động của khách trên web)', '事件', 'evento', 'sự kiện', 'common')
  on conflict (id) do update set term = excluded.term, level = excluded.level, pos = excluded.pos, ipa = excluded.ipa, def_en = excluded.def_en,
    meaning_vi = excluded.meaning_vi, meaning_zh = excluded.meaning_zh, meaning_es = excluded.meaning_es, quiz_vi = excluded.quiz_vi;
-- Module 10
insert into pages (id, section_id, name, sort, name_en) values ('nb_dm_l02_s1_p10', 'nb_dm_l02_s1', '🏁 10 — Tối ưu & bài cuối', 11, '10 — Optimisation & capstone') on conflict (id) do update set name = excluded.name, sort = excluded.sort, name_en = excluded.name_en;
insert into batches (id, page_id, name, sort, created_at, name_en) values ('nb_dm_l02_s1_p10_b1', 'nb_dm_l02_s1_p10', 'Từ vựng', 1, 1791100000000, 'Vocabulary') on conflict (id) do update set name = excluded.name;
insert into blocks (id, batch_id, name, global_index, sort) values ('nb_dm_l02_s1_p10_b1_bl1', 'nb_dm_l02_s1_p10_b1', 'Block 1', 11, 1) on conflict (id) do update set name = excluded.name;
insert into words (id, block_id, sort, term, level, pos, ipa, def_en, meaning_vi, meaning_zh, meaning_es, quiz_vi, freq) values
  ('nb_dm_l02_s1_p10_b1_bl1_w1', 'nb_dm_l02_s1_p10_b1_bl1', 1, 'optimisation', 'C1', 'Noun', '/ˌɒptɪmaɪˈzeɪʃən/', 'Making small changes again and again to get better results.', 'tối ưu hoá', '优化', 'optimización', 'tối ưu hoá', 'common'),
  ('nb_dm_l02_s1_p10_b1_bl1_w2', 'nb_dm_l02_s1_p10_b1_bl1', 2, 'A/B test', 'B2', 'Noun phrase', '', 'Comparing two versions to see which one works better.', 'thử nghiệm A/B (so 2 phiên bản)', 'A/B 测试', 'prueba A/B', 'thử nghiệm A/B', 'common'),
  ('nb_dm_l02_s1_p10_b1_bl1_w3', 'nb_dm_l02_s1_p10_b1_bl1', 3, 'variable', 'B2', 'Noun', '/ˈveəriəbəl/', 'The one thing you change in a test, like the headline or image.', 'yếu tố thay đổi khi thử nghiệm', '变量', 'variable', 'yếu tố thay đổi khi thử nghiệm', 'common'),
  ('nb_dm_l02_s1_p10_b1_bl1_w4', 'nb_dm_l02_s1_p10_b1_bl1', 4, 'iteration', 'C1', 'Noun', '/ˌɪtəˈreɪʃən/', 'One round of testing, measuring and improving.', 'một vòng lặp cải tiến', '迭代', 'iteración', 'một vòng lặp cải tiến', 'common'),
  ('nb_dm_l02_s1_p10_b1_bl1_w5', 'nb_dm_l02_s1_p10_b1_bl1', 5, 'benchmark', 'C1', 'Noun', '/ˈbentʃmɑːk/', 'A standard number used for comparison.', 'mức chuẩn để so sánh', '基准', 'referencia', 'mức chuẩn để so sánh', 'common'),
  ('nb_dm_l02_s1_p10_b1_bl1_w6', 'nb_dm_l02_s1_p10_b1_bl1', 6, 'hypothesis', 'C1', 'Noun', '/haɪˈpɒθəsɪs/', 'An idea you test to see if it is true.', 'giả thuyết', '假设', 'hipótesis', 'giả thuyết', 'common'),
  ('nb_dm_l02_s1_p10_b1_bl1_w7', 'nb_dm_l02_s1_p10_b1_bl1', 7, 'scale up', 'B2', 'Phrasal verb', '/skeɪl ʌp/', 'To increase budget or size after something works.', 'mở rộng quy mô', '扩大规模', 'escalar', 'mở rộng quy mô', 'common'),
  ('nb_dm_l02_s1_p10_b1_bl1_w8', 'nb_dm_l02_s1_p10_b1_bl1', 8, 'retargeting', 'C1', 'Noun', '/riːˈtɑːɡɪtɪŋ/', 'Showing ads to people who visited before but did not buy.', 'quảng cáo bám đuổi', '再营销', 'retargeting', 'quảng cáo bám đuổi', 'common'),
  ('nb_dm_l02_s1_p10_b1_bl1_w9', 'nb_dm_l02_s1_p10_b1_bl1', 9, 'mini-funnel', 'B2', 'Noun', '', 'A small, complete funnel for one product, from ad to repeat purchase.', 'phễu nhỏ hoàn chỉnh', '迷你漏斗', 'mini embudo', 'phễu nhỏ hoàn chỉnh', 'common'),
  ('nb_dm_l02_s1_p10_b1_bl1_w10', 'nb_dm_l02_s1_p10_b1_bl1', 10, 'checklist', 'B1', 'Noun', '/ˈtʃeklɪst/', 'A list of things to check before calling a task finished.', 'danh sách kiểm tra', '检查清单', 'lista de verificación', 'danh sách kiểm tra', 'common')
  on conflict (id) do update set term = excluded.term, level = excluded.level, pos = excluded.pos, ipa = excluded.ipa, def_en = excluded.def_en,
    meaning_vi = excluded.meaning_vi, meaning_zh = excluded.meaning_zh, meaning_es = excluded.meaning_es, quiz_vi = excluded.quiz_vi;
commit;
-- Kiểm tra: select h.sort, h.name from hubs h order by h.sort;   select count(*) from words where id like 'nb_dm_l02%';  -- phải = 110
