"""Dữ liệu Hub 📈 DIGITAL MARKETING (khoá L02-digital-marketing-beginner, 11 module 00-10).
Mỗi module = 1 Page -> 1 Batch "Từ vựng" -> 1 Block 10 từ.
Mỗi từ: (term, pos, level, ipa, def_en, meaning_vi, meaning_zh, meaning_es)."""

MODULES = [
 ("00", "⚙️ 00 — Cài đặt công cụ", "00 — Tool setup", [
  ("ad account", "Noun phrase", "B1", "", "An account used to create and pay for online ads.", "tài khoản quảng cáo", "广告账户", "cuenta publicitaria"),
  ("Business Manager", "Noun phrase", "B2", "", "Meta's tool for managing pages, ad accounts and team access in one place.", "trình quản lý doanh nghiệp (Meta)", "商务管理平台", "administrador comercial"),
  ("Official Account (OA)", "Noun phrase", "B2", "", "A verified business account on Zalo used to chat with and message customers.", "tài khoản chính thức (Zalo OA)", "官方账号", "cuenta oficial"),
  ("property", "Noun", "B2", "/ˈprɒpəti/", "In Google Analytics, one report space for one website or app.", "tài sản (cuốn sổ báo cáo trong GA4)", "媒体资源", "propiedad"),
  ("data stream", "Noun phrase", "B2", "", "A source that sends visitor data from a website or app into Analytics.", "luồng dữ liệu", "数据流", "flujo de datos"),
  ("measurement ID", "Noun phrase", "B2", "", "The code starting with G- that links a website to a GA4 property.", "mã đo lường (G-...)", "衡量 ID", "ID de medición"),
  ("tag", "Noun", "B1", "/tæɡ/", "A small piece of code added to a web page to collect data.", "thẻ (đoạn mã theo dõi)", "代码标签", "etiqueta"),
  ("dashboard", "Noun", "B1", "/ˈdæʃbɔːd/", "A screen that shows the main numbers and charts at a glance.", "bảng tổng hợp số liệu", "仪表板", "panel de control"),
  ("real-time report", "Noun phrase", "B2", "", "A report that shows what visitors are doing on a site right now.", "báo cáo thời gian thực", "实时报告", "informe en tiempo real"),
  ("pixel", "Noun", "B2", "/ˈpɪksəl/", "Tracking code from an ad platform that records what visitors do after clicking an ad.", "pixel theo dõi (mã đo của nền tảng quảng cáo)", "像素代码", "píxel de seguimiento"),
 ]),
 ("01", "🧭 01 — Tổng quan & hành trình khách hàng", "01 — Overview & customer journey", [
  ("digital marketing", "Noun phrase", "B1", "", "Promoting products or services using the internet and digital devices.", "tiếp thị kỹ thuật số", "数字营销", "marketing digital"),
  ("customer journey", "Noun phrase", "B2", "", "All the steps a customer goes through from first hearing about a product to buying it and after.", "hành trình khách hàng", "客户旅程", "recorrido del cliente"),
  ("touchpoint", "Noun", "B2", "/ˈtʌtʃpɔɪnt/", "Any moment where a customer comes into contact with a brand.", "điểm chạm", "接触点", "punto de contacto"),
  ("channel", "Noun", "B1", "/ˈtʃænəl/", "A route used to reach customers, such as Facebook, Zalo or email.", "kênh", "渠道", "canal"),
  ("target audience", "Noun phrase", "B1", "", "The specific group of people a business wants to reach.", "khách hàng mục tiêu", "目标受众", "público objetivo"),
  ("brand awareness", "Noun phrase", "B2", "", "How well people know and recognise a brand.", "mức độ nhận biết thương hiệu", "品牌知名度", "reconocimiento de marca"),
  ("word of mouth", "Noun phrase", "B2", "", "When people tell others about a product from their own experience.", "truyền miệng", "口碑", "boca a boca"),
  ("price comparison", "Noun phrase", "B1", "", "Checking the price of the same product in several shops before buying.", "so sánh giá", "比价", "comparación de precios"),
  ("decision-making", "Noun", "B2", "/dɪˈsɪʒən ˌmeɪkɪŋ/", "The process of choosing what to buy or do.", "việc ra quyết định", "决策", "toma de decisiones"),
  ("online presence", "Noun phrase", "B2", "", "How visible a business is on the internet.", "sự hiện diện trực tuyến", "线上存在感", "presencia en línea"),
 ]),
 ("02", "🔻 02 — Phễu bán hàng (Funnel)", "02 — Marketing funnel", [
  ("funnel", "Noun", "B2", "/ˈfʌnəl/", "A model of the steps from first seeing a brand to buying and buying again.", "phễu bán hàng", "营销漏斗", "embudo de ventas"),
  ("awareness", "Noun", "B2", "/əˈweənəs/", "The first stage, when people first learn that a brand exists.", "giai đoạn nhận biết", "认知阶段", "reconocimiento"),
  ("consideration", "Noun", "B2", "/kənˌsɪdəˈreɪʃən/", "The stage when people compare options and think about buying.", "giai đoạn cân nhắc", "考虑阶段", "consideración"),
  ("conversion", "Noun", "B2", "/kənˈvɜːʃən/", "When a person takes the action you want, such as buying or signing up.", "chuyển đổi (khách làm hành động mong muốn)", "转化", "conversión"),
  ("retention", "Noun", "C1", "/rɪˈtenʃən/", "Keeping existing customers so they buy again.", "giữ chân khách hàng", "客户留存", "retención"),
  ("lead", "Noun", "B2", "/liːd/", "A person who has shown interest and left contact details.", "khách hàng tiềm năng (đã để lại thông tin)", "潜在客户", "cliente potencial"),
  ("drop-off", "Noun", "C1", "/ˈdrɒp ɒf/", "The point where many people leave the funnel without continuing.", "chỗ rớt khách", "流失点", "abandono"),
  ("landing page", "Noun phrase", "B2", "", "The web page people arrive at after clicking an ad or link.", "trang đích", "落地页", "página de destino"),
  ("call to action (CTA)", "Noun phrase", "B2", "", "A short message or button telling people what to do next, like 'Buy now'.", "lời kêu gọi hành động", "行动号召", "llamada a la acción"),
  ("TOFU / MOFU / BOFU", "Abbreviation", "C1", "", "Top, middle and bottom of the funnel.", "đầu / giữa / đáy phễu", "漏斗顶部/中部/底部", "parte alta / media / baja del embudo"),
 ]),
 ("03", "👤 03 — Chân dung khách hàng (Persona)", "03 — Buyer persona", [
  ("buyer persona", "Noun phrase", "B2", "", "A detailed profile of a typical customer, based on real data.", "chân dung khách hàng", "买家画像", "buyer persona"),
  ("pain point", "Noun phrase", "B2", "", "A problem or frustration a customer wants to solve.", "nỗi đau (vấn đề khách đang gặp)", "痛点", "punto de dolor"),
  ("demographics", "Noun", "B2", "/ˌdeməˈɡræfɪks/", "Facts about people such as age, gender, income and location.", "đặc điểm nhân khẩu học (tuổi, giới tính, thu nhập…)", "人口统计特征", "datos demográficos"),
  ("motivation", "Noun", "B1", "/ˌməʊtɪˈveɪʃən/", "The reason that makes someone want to buy.", "động lực", "动机", "motivación"),
  ("objection", "Noun", "B2", "/əbˈdʒekʃən/", "A reason a customer gives for not buying yet.", "lý do còn ngần ngại", "顾虑", "objeción"),
  ("market research", "Noun phrase", "B2", "", "Collecting information about customers and competitors.", "nghiên cứu thị trường", "市场调研", "investigación de mercado"),
  ("survey", "Noun", "B1", "/ˈsɜːveɪ/", "A set of questions asked to many people to collect opinions.", "khảo sát", "问卷调查", "encuesta"),
  ("competitor", "Noun", "B1", "/kəmˈpetɪtə/", "Another business that sells similar products.", "đối thủ cạnh tranh", "竞争对手", "competidor"),
  ("assumption", "Noun", "B2", "/əˈsʌmpʃən/", "Something you believe is true without proof.", "giả định (đoán, chưa có bằng chứng)", "假设", "suposición"),
  ("insight", "Noun", "B2", "/ˈɪnsaɪt/", "A useful understanding about customers found from data.", "điều nhận ra (từ dữ liệu)", "洞察", "hallazgo"),
 ]),
 ("04", "🗺️ 04 — Chọn nền tảng ở Việt Nam", "04 — Vietnam platform ecosystem", [
  ("platform", "Noun", "B1", "/ˈplætfɔːm/", "An online service where businesses reach users, such as TikTok or Shopee.", "nền tảng", "平台", "plataforma"),
  ("social media", "Noun phrase", "B1", "", "Websites and apps where people share content and talk to each other.", "mạng xã hội", "社交媒体", "redes sociales"),
  ("e-commerce", "Noun", "B2", "/ˌiː ˈkɒmɜːs/", "Buying and selling products online.", "thương mại điện tử", "电子商务", "comercio electrónico"),
  ("marketplace", "Noun", "B2", "/ˈmɑːkɪtpleɪs/", "A website where many sellers offer products, like Shopee or Lazada.", "sàn thương mại điện tử", "电商平台", "mercado en línea"),
  ("search engine", "Noun phrase", "B1", "", "A website like Google that finds information when you type words.", "công cụ tìm kiếm", "搜索引擎", "motor de búsqueda"),
  ("user base", "Noun phrase", "B2", "", "All the people who use a platform.", "lượng người dùng", "用户群", "base de usuarios"),
  ("search intent", "Noun phrase", "C1", "", "What a person really wants when they search for something.", "ý định tìm kiếm", "搜索意图", "intención de búsqueda"),
  ("channel mix", "Noun phrase", "C1", "", "The combination of channels a business uses together.", "tổ hợp kênh", "渠道组合", "combinación de canales"),
  ("short-form video", "Noun phrase", "B2", "", "Short videos, usually under one minute, like TikTok or Reels.", "video ngắn", "短视频", "vídeo corto"),
  ("resources", "Noun", "B1", "/rɪˈzɔːsɪz/", "The time, money and people available to do the work.", "nguồn lực", "资源", "recursos"),
 ]),
 ("05", "📘 05 — Quảng cáo Facebook & Instagram", "05 — Facebook & Instagram Ads", [
  ("campaign", "Noun", "B1", "/kæmˈpeɪn/", "A planned set of ads with one main goal.", "chiến dịch", "广告系列", "campaña"),
  ("ad set", "Noun phrase", "B2", "", "The level that controls audience, budget and schedule for a group of ads.", "nhóm quảng cáo", "广告组", "conjunto de anuncios"),
  ("objective", "Noun", "B2", "/əbˈdʒektɪv/", "The goal you choose for a campaign, such as traffic or sales.", "mục tiêu (của chiến dịch)", "广告目标", "objetivo"),
  ("targeting", "Noun", "B2", "/ˈtɑːɡɪtɪŋ/", "Choosing which people will see your ads.", "nhắm chọn đối tượng", "定向", "segmentación"),
  ("lookalike audience", "Noun phrase", "C1", "", "New people who are similar to your existing customers.", "đối tượng tương tự", "类似受众", "público similar"),
  ("custom audience", "Noun phrase", "C1", "", "People who already interacted with your business, like visitors or buyers.", "đối tượng tuỳ chỉnh (người đã tương tác)", "自定义受众", "público personalizado"),
  ("daily budget", "Noun phrase", "B1", "", "The average amount of money you spend on ads each day.", "ngân sách mỗi ngày", "每日预算", "presupuesto diario"),
  ("placement", "Noun", "B2", "/ˈpleɪsmənt/", "Where your ad appears, such as Feed, Stories or Reels.", "vị trí hiển thị quảng cáo", "版位", "ubicación"),
  ("ad creative", "Noun phrase", "B2", "", "The image, video and text that make up an ad.", "nội dung quảng cáo (hình, video, chữ)", "广告创意", "creatividad publicitaria"),
  ("reach", "Noun", "B1", "/riːtʃ/", "The number of different people who saw your ad.", "lượt tiếp cận", "覆盖人数", "alcance"),
 ]),
 ("06", "🎵 06 — Quảng cáo TikTok, Google & Zalo", "06 — TikTok, Google & Zalo Ads", [
  ("keyword", "Noun", "B1", "/ˈkiːwɜːd/", "A word or phrase people type into a search engine.", "từ khoá", "关键词", "palabra clave"),
  ("search ads", "Noun phrase", "B2", "", "Ads that appear when people search for certain words on Google.", "quảng cáo tìm kiếm", "搜索广告", "anuncios de búsqueda"),
  ("display ads", "Noun phrase", "B2", "", "Image or banner ads shown on websites and apps.", "quảng cáo hiển thị (banner)", "展示广告", "anuncios de display"),
  ("bid", "Noun", "B2", "/bɪd/", "The most you are willing to pay for a click or result.", "giá thầu", "出价", "puja"),
  ("negative keyword", "Noun phrase", "C1", "", "A word you add so your ad does NOT show for searches containing it.", "từ khoá phủ định", "否定关键词", "palabra clave negativa"),
  ("in-feed ad", "Noun phrase", "B2", "", "An ad that appears between normal videos or posts in a feed.", "quảng cáo xen giữa bảng tin", "信息流广告", "anuncio en el feed"),
  ("hook", "Noun", "B2", "/hʊk/", "The first seconds of a video that grab attention.", "câu mở đầu giữ chân người xem", "开头钩子", "gancho"),
  ("Performance Max", "Noun phrase", "C1", "", "A Google Ads campaign type that runs across all Google channels automatically.", "chiến dịch tối đa hoá hiệu suất (Google)", "效果最大化广告系列", "Máximo rendimiento"),
  ("message ads", "Noun phrase", "B2", "", "Ads that open a chat with the business when clicked.", "quảng cáo mở tin nhắn", "消息广告", "anuncios de mensajes"),
  ("ad auction", "Noun phrase", "C1", "", "The process a platform uses to decide which ads to show and at what price.", "phiên đấu giá quảng cáo", "广告竞价", "subasta de anuncios"),
 ]),
 ("07", "🔍 07 — SEO & viết bài cho website", "07 — SEO & website content", [
  ("SEO", "Abbreviation", "B2", "/ˌes iː ˈəʊ/", "Search Engine Optimisation: improving a site so it ranks higher in free search results.", "tối ưu hoá công cụ tìm kiếm", "搜索引擎优化", "posicionamiento en buscadores"),
  ("organic traffic", "Noun phrase", "B2", "", "Visitors who come from free search results, not from ads.", "lượt truy cập tự nhiên (không trả tiền)", "自然流量", "tráfico orgánico"),
  ("on-page SEO", "Noun phrase", "C1", "", "SEO work done on the page itself, like titles, headings and content.", "SEO trên trang", "页面内优化", "SEO on-page"),
  ("meta description", "Noun phrase", "C1", "", "The short summary of a page shown under its title in search results.", "đoạn mô tả hiện trên Google", "元描述", "meta descripción"),
  ("ranking", "Noun", "B2", "/ˈræŋkɪŋ/", "The position of a page in search results.", "thứ hạng", "排名", "posicionamiento"),
  ("backlink", "Noun", "C1", "/ˈbæklɪŋk/", "A link from another website to your website.", "liên kết từ trang khác trỏ về", "外链", "enlace entrante"),
  ("content pillar", "Noun phrase", "C1", "", "A main topic that many related posts are built around.", "trụ cột nội dung (chủ đề chính)", "内容支柱", "pilar de contenido"),
  ("long-tail keyword", "Noun phrase", "C1", "", "A longer, more specific search phrase with fewer but better searches.", "từ khoá dài (cụ thể)", "长尾关键词", "palabra clave de cola larga"),
  ("search volume", "Noun phrase", "B2", "", "How many times people search for a keyword each month.", "lượng tìm kiếm", "搜索量", "volumen de búsqueda"),
  ("blog post", "Noun phrase", "B1", "", "An article published on a website's blog.", "bài viết blog", "博客文章", "entrada de blog"),
 ]),
 ("08", "💬 08 — Xây kênh & cộng đồng", "08 — Channels & community", [
  ("engagement", "Noun", "B2", "/ɪnˈɡeɪdʒmənt/", "Likes, comments, shares and other ways people interact with content.", "lượt tương tác", "互动", "interacción"),
  ("community", "Noun", "B1", "/kəˈmjuːnəti/", "A group of people who share an interest and talk with each other.", "cộng đồng", "社群", "comunidad"),
  ("follower", "Noun", "B1", "/ˈfɒləʊə/", "A person who chooses to see a page's or account's posts.", "người theo dõi", "粉丝", "seguidor"),
  ("content calendar", "Noun phrase", "B2", "", "A schedule showing what will be posted and when.", "lịch nội dung", "内容日历", "calendario de contenidos"),
  ("algorithm", "Noun", "B2", "/ˈælɡərɪðəm/", "The rules a platform uses to decide which posts people see.", "thuật toán", "算法", "algoritmo"),
  ("user-generated content (UGC)", "Noun phrase", "C1", "", "Content made by customers, such as reviews or photos.", "nội dung do khách hàng tạo", "用户生成内容", "contenido generado por usuarios"),
  ("broadcast message", "Noun phrase", "B2", "", "One message sent to many followers at once, like on Zalo OA.", "tin nhắn gửi hàng loạt", "群发消息", "mensaje masivo"),
  ("moderator", "Noun", "B2", "/ˈmɒdəreɪtə/", "A person who manages a group and keeps discussions friendly.", "người kiểm duyệt nhóm", "版主", "moderador"),
  ("posting frequency", "Noun phrase", "B2", "", "How often an account publishes new posts.", "tần suất đăng bài", "发布频率", "frecuencia de publicación"),
  ("organic reach", "Noun phrase", "C1", "", "The number of people who see a post without paid promotion.", "lượt tiếp cận tự nhiên", "自然覆盖", "alcance orgánico"),
 ]),
 ("09", "📊 09 — Đo lường & phân tích", "09 — Measurement & analytics", [
  ("KPI", "Abbreviation", "B2", "/ˌkeɪ piː ˈaɪ/", "Key Performance Indicator: the main number used to judge success.", "chỉ số đo hiệu quả chính", "关键绩效指标", "indicador clave de rendimiento"),
  ("impression", "Noun", "B2", "/ɪmˈpreʃən/", "One time an ad is shown on a screen.", "lượt hiển thị", "展示次数", "impresión"),
  ("CTR", "Abbreviation", "C1", "/ˌsiː tiː ˈɑː/", "Click-through rate: clicks divided by impressions.", "tỉ lệ nhấp", "点击率", "tasa de clics"),
  ("CPC", "Abbreviation", "C1", "/ˌsiː piː ˈsiː/", "Cost per click: money spent divided by clicks.", "chi phí mỗi lượt nhấp", "每次点击费用", "coste por clic"),
  ("CPA", "Abbreviation", "C1", "/ˌsiː piː ˈeɪ/", "Cost per action: money spent divided by conversions.", "chi phí mỗi chuyển đổi", "每次转化费用", "coste por adquisición"),
  ("ROAS", "Abbreviation", "C1", "/ˈrəʊæs/", "Return on ad spend: revenue from ads divided by ad cost.", "doanh thu trên chi phí quảng cáo", "广告支出回报率", "retorno de la inversión publicitaria"),
  ("conversion rate", "Noun phrase", "B2", "", "The percentage of visitors who take the desired action.", "tỉ lệ chuyển đổi", "转化率", "tasa de conversión"),
  ("UTM parameter", "Noun phrase", "C1", "", "Tags added to a link to show which source and campaign a visitor came from.", "tham số UTM (gắn vào link để biết khách từ đâu tới)", "UTM 参数", "parámetro UTM"),
  ("bounce rate", "Noun phrase", "C1", "", "The percentage of visitors who leave after seeing only one page.", "tỉ lệ thoát", "跳出率", "tasa de rebote"),
  ("event", "Noun", "B1", "/ɪˈvent/", "In GA4, one action a visitor takes, such as a click or a purchase.", "sự kiện (hành động của khách trên web)", "事件", "evento"),
 ]),
 ("10", "🏁 10 — Tối ưu & bài cuối", "10 — Optimisation & capstone", [
  ("optimisation", "Noun", "C1", "/ˌɒptɪmaɪˈzeɪʃən/", "Making small changes again and again to get better results.", "tối ưu hoá", "优化", "optimización"),
  ("A/B test", "Noun phrase", "B2", "", "Comparing two versions to see which one works better.", "thử nghiệm A/B (so 2 phiên bản)", "A/B 测试", "prueba A/B"),
  ("variable", "Noun", "B2", "/ˈveəriəbəl/", "The one thing you change in a test, like the headline or image.", "yếu tố thay đổi khi thử nghiệm", "变量", "variable"),
  ("iteration", "Noun", "C1", "/ˌɪtəˈreɪʃən/", "One round of testing, measuring and improving.", "một vòng lặp cải tiến", "迭代", "iteración"),
  ("benchmark", "Noun", "C1", "/ˈbentʃmɑːk/", "A standard number used for comparison.", "mức chuẩn để so sánh", "基准", "referencia"),
  ("hypothesis", "Noun", "C1", "/haɪˈpɒθəsɪs/", "An idea you test to see if it is true.", "giả thuyết", "假设", "hipótesis"),
  ("scale up", "Phrasal verb", "B2", "/skeɪl ʌp/", "To increase budget or size after something works.", "mở rộng quy mô", "扩大规模", "escalar"),
  ("retargeting", "Noun", "C1", "/riːˈtɑːɡɪtɪŋ/", "Showing ads to people who visited before but did not buy.", "quảng cáo bám đuổi", "再营销", "retargeting"),
  ("mini-funnel", "Noun", "B2", "", "A small, complete funnel for one product, from ad to repeat purchase.", "phễu nhỏ hoàn chỉnh", "迷你漏斗", "mini embudo"),
  ("checklist", "Noun", "B1", "/ˈtʃeklɪst/", "A list of things to check before calling a task finished.", "danh sách kiểm tra", "检查清单", "lista de verificación"),
 ]),
]
